name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Prod

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build the Quarkus App
      run: ./gradlew build -x test

    - name: Log in to Google Cloud Container Registry
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet
        SHA_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        IMAGE_NAME=europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/feature-toggle-backend/feature-toggle-backend
        docker build . --file src/main/docker/Dockerfile.jvm -t ${IMAGE_NAME}:${SHA_TAG}
        docker tag ${IMAGE_NAME}:${SHA_TAG} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}:${SHA_TAG}
        docker push ${IMAGE_NAME}:latest

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'feature-toggle-backend'
        image: 'europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/feature-toggle-backend/feature-toggle-backend:latest'
        region: 'europe-west3'

